### ISSUE TITLE
[Feature Request] Custom highlight.js URL

### ISSUE THREAD

**Issue by h6ah4i** [digitalcraftsman/hugo-material-docs#46]
Hi. Thanks for the superb theme. I am making my library's document site with this theme.

Currently`//gohugo.io/js/highlight.pack.js` is hard-coded in `footer_js.html` but I want to replace it with custom packaged one which supports more languages.

How about adding an option to specify `highlight.js` file like the following?

```toml
[params]
    # Syntax highlighting javascript
    highlight_js  = "[highlight.js url goes here]"
```

Thanks.
