### ISSUE TITLE
How to navigate

### ISSUE THREAD

**Issue by willin** [digitalcraftsman/hugo-material-docs#58]
tree view

```
.
└──ontent
    ├── index.md
    └── section
        ├── good-to-great.md
        └── index.md
```

config:

```toml
[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "section/"
	weight = 10
```

Q1: if i set like this,  `good-to-great.md` never shown.

Q2: how about 3 level section folders?

like gitbook config: 

```markdown
- [Chapter 1](c1/index.md)
    - [Section 1](c1/s1/index.md)
        - [SubSection 1](c1/s1/ss1.md)
```
